### ISSUE TITLE
thprac 2.1 no longer recognises EOSD?

### ISSUE THREAD

**Issue by webbedspace** [touhouworldcup/thprac#40]
The exe is named `東方紅魔郷.exe`, the system locale is Japanese, and yet, thprac 2.1 doesn't recognise EOSD, before or after launching, with or without thcrap, even though ack's previous thprac version did.

**Comment by toimine** [comment]
weird, it did recognise my eosd tho, i got it from nyaa si if that matters

**Comment by 32th-System** [comment]
It makes sense that EoSD wouldn't be recognized at the moment. Some of the strings in the source code were (and might still be) encoded in GB2312, because the previous developer wrote those source files on a PC with Chinese locale. Then I compiled the the exe on my PC with a German locale without converting all the strings to UTF-8. I converted some more uses of 東方紅魔郷.exe to Unicode in [this commit](https://github.com/touhouworldcup/thprac/commit/7d11ff81071561c87a8c157bbc4f2d8d0ab779db) so everything should work next version

**Comment by 32th-System** [comment]
New version out and more strings were converted to Unicode. Is your problem fixed now?

**Comment by webbedspace** [comment]
Still doesn't work in 2.1.1.…!

Some more details about my EOSD copy:
```
Name: 東方紅魔郷.exe
Size: 512000 bytes (500 KiB)
CRC32: AEB8799E
CRC64: 3AAFFD30573876DF
SHA256: 9f76483c46256804792399296619c1274363c31cd8f1775fafb55106fb852245
SHA1: e61b4f4fea3802e926ef307f45166599c3e86555
```

**Comment by 32th-System** [comment]
Can you try with this build? (when the next stable thprac releases, this version will auto-update to it) [thprac.zip](https://github.com/touhouworldcup/thprac/files/8933588/thprac.zip)
